version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: lms-mysql
    environment:
      MYSQL_ROOT_PASSWORD: your_secure_mysql_password_here
      MYSQL_DATABASE: lms_db
      MYSQL_USER: lms_user
      MYSQL_PASSWORD: your_secure_mysql_password_here
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./nestjs-backend/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    networks:
      - lms-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  redis-cache:
    image: redis:7-alpine
    container_name: lms-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - lms-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 3s
      retries: 5

  meilisearch:
    image: getmeili/meilisearch:v1.5
    container_name: lms-meilisearch
    environment:
      MEILI_MASTER_KEY: lms_search_master_key_2024_secure
      MEILI_ENV: production
    ports:
      - "7700:7700"
    volumes:
      - meilisearch_data:/meili_data
    networks:
      - lms-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7700/health"]
      interval: 30s
      timeout: 3s
      retries: 5

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local
  meilisearch_data:
    driver: local

networks:
  lms-network:
    driver: bridge
